/**
 * Generate a budget summary PDF for mortgage applications.
 * Clean text-based report — income, outgoings, disposable income.
 */
import { jsPDF } from 'jspdf';

export function exportBudgetPDF(budgetConfig, netMonthlyPay) {
  const items = budgetConfig?.budgetedItems || [];
  const accounts = budgetConfig?.savingsAccounts || [];
  const savingsMonthly = accounts.reduce((s, a) => s + Number(a.monthlyContribution || 0), 0);

  // Calculate totals
  const byCategory = {};
  let totalOutgoings = 0;
  items.forEach(item => {
    const monthly = item.frequency === 'annual' ? (item.amount || 0) / 12 : (item.amount || 0);
    byCategory[item.category] = (byCategory[item.category] || 0) + monthly;
    totalOutgoings += monthly;
  });
  totalOutgoings += savingsMonthly;
  const disposable = netMonthlyPay - totalOutgoings;

  const fmt = (n) => '£' + Number(n || 0).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const CATEGORY_LABELS = {
    housing: 'Housing', utilities: 'Utilities', transport: 'Transport',
    food: 'Food & Groceries', subscriptions: 'Subscriptions', debt: 'Debt',
    discretionary: 'Discretionary', savings: 'Savings', other: 'Other',
  };

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const w = 190; // usable width
  let y = 20;
  const margin = 10;

  const title = (text, size = 16, style = 'bold') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.text(text, margin, y);
    y += size * 0.5;
  };
  const text = (text, size = 10, style = 'normal', align = 'left') => {
    doc.setFontSize(size);
    doc.setFont('helvetica', style);
    doc.text(text, align === 'left' ? margin : 200 - margin, y, { align });
  };
  const line = () => {
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, 200 - margin, y);
    y += 4;
  };
  const row = (label, value, size = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    doc.text(label, margin, y);
    doc.setFont('helvetica', 'bold');
    doc.text(value, 200 - margin, y, { align: 'right' });
    y += size * 0.6;
  };
  const spacer = (h = 4) => { y += h; };

  // === HEADER ===
  title('Budget Summary', 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by TaxSense — ' + new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }), margin, y);
  y += 6;
  doc.setTextColor(40, 40, 40);

  line();

  // === INCOME ===
  title('Monthly Income', 14);
  row('Net Take-Home Pay', fmt(netMonthlyPay), 11);
  spacer(6);

  line();

  // === OUTGOINGS ===
  title('Monthly Outgoings', 14);
  spacer(2);

  // Group items by category
  const categoryItems = {};
  items.forEach(item => {
    const cat = item.category || 'other';
    if (!categoryItems[cat]) categoryItems[cat] = [];
    categoryItems[cat].push(item);
  });

  let categoryRendered = false;
  Object.entries(categoryItems).forEach(([cat, catItems]) => {
    const catLabel = CATEGORY_LABELS[cat] || cat;
    const catTotal = catItems.reduce((s, i) => s + (i.frequency === 'annual' ? (i.amount || 0) / 12 : (i.amount || 0)), 0);

    // Category header
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text(catLabel, margin + 2, y);
    y += 5;

    // Items
    catItems.forEach(item => {
      const monthly = item.frequency === 'annual' ? (item.amount || 0) / 12 : (item.amount || 0);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.text('  ' + item.name, margin + 4, y);
      doc.setFont('helvetica', 'normal');
      doc.text(fmt(monthly), 200 - margin, y, { align: 'right' });
      y += 4;
    });
    categoryRendered = true;
  });

  // Savings contribution line (if any)
  if (savingsMonthly > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
    doc.text('Savings', margin + 2, y);
    y += 5;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text('  Monthly contributions', margin + 4, y);
    doc.text(fmt(savingsMonthly), 200 - margin, y, { align: 'right' });
    y += 4;
  }

  spacer(2);

  // Total outgoings
  line();
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(200, 60, 60);
  doc.text('Total Monthly Outgoings', margin, y);
  doc.text(fmt(totalOutgoings), 200 - margin, y, { align: 'right' });
  y += 7;

  // === DISPOSABLE INCOME ===
  line();
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(disposable >= 0 ? 30 : 200, disposable >= 0 ? 120 : 60, disposable >= 0 ? 80 : 60);
  doc.text('Disposable Income', margin, y);
  doc.text(fmt(disposable) + '/mo', 200 - margin, y, { align: 'right' });
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Annual Surplus: ' + fmt(disposable * 12), margin, y);
  y += 12;

  // === FUTNUOTES ===
  line();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(160, 160, 160);
  doc.text('This budget summary is for information purposes only and does not constitute financial advice.', margin, y);
  y += 3;
  doc.text('Income figures are based on the tax calculations in TaxSense and are not guaranteed.', margin, y);
  y += 6;

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text('Generated by TaxSense v1.x', margin, 290);
  doc.text(new Date().toISOString().slice(0, 10), 200 - margin, 290, { align: 'right' });

  // Save
  doc.save('Budget-Summary.pdf');
}
